-- AlterEnum
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'BIRTH_CERTIFICATE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'EDUCATIONAL_CERTIFICATE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'DRIVING_LICENSE';
